name = "DesignStructureMatrix"
uuid = "19401b82-8c43-11e9-36fe-e7e08b9911f1"
authors = ["Otepipi"]
version = "0.1.0"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
